apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnjhgf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnjhgf
  template:
    metadata:
      labels:
        app: mnjhgf
    spec:
      containers:
      - image: okteto.dev/mnjhgf:latest
        name: mnjhgf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "22b8df4a-0a84-11ed-861d-0242ac120002"
        - name: Vless_Path
          value: "/vl098"
        - name: Vmess_UUID
          value: "22b8df4a-0a84-11ed-861d-0242ac120002"
        - name: Vmess_Path
          value: "/vm235"
        - name: Share_Path
          value: "/v2link"
